### ISSUE TITLE
'*' does not work for me

### ISSUE THREAD

**Issue by svenXY** [LuRsT/hr#47]
Hi,

outputting a line of asterikses like suggested in the README does not work for me, but the following:
```sh
> ls -l
insgesamt 4
-rw-r--r-- 1 svh svh    0 24. Feb 11:21 aaa
-rw-r--r-- 1 svh svh    0 24. Feb 11:21 bbb
-rw-r--r-- 1 svh svh    0 24. Feb 11:21 ccc
drwxr-xr-x 2 svh svh 4096 24. Feb 11:21 ddd
> hr '*'
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
```

which is clearly not intended.

What am I doing wrong?

Thanks,
Sven

**Comment by jomo** [comment]
Your shell performs pattern matching on the asterisk, although it is quoted. Weird.
Which shell do you use?

**Comment by LuRsT** [comment]
Hi @svenXY,

As @jomo said, it's probably your shell doing expansion before passing it to the script, you can test this easily to see it for yourself:

    $ echo '*'

I bet you will get `aaa bbb ccc ddd` if your shell is indeed expanding it. I don't know which shell you are using, but you can try with double quotes to see if it doesn't expand anymore.

In bash and zsh, these are my results:

    $ ls
    aaa  bbb  ccc  ddd
    $ echo "*"
    *
    $ echo '*'
    *
    $ echo *
    aaa  bbb  ccc  ddd

**Comment by svenXY** [comment]
Yes, it does expand the asterisk although it is quoted:

```sh
> echo $SHELL
/usr/bin/zsh
> hr.sh '*'
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ddddddddddddddddddddddddddddddddddddddddddddddddddd
> echo '*'
*
> bash
$ echo '*'
*
$ hr.sh '*'
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
dddddddddddddddddddddddddddddddddddddddddddddddddddd
```

See? Problem persists.

FWIW: I also tried the hr.py approach and it works fine.

**Comment by LuRsT** [comment]
Hmmmm, that is very interesting, I can't reproduce that behaviour with my zsh, could you make sure that you have the latest version of hr?

Also, you can try these different scenarios:
- Move ~/.zshrc to some other file to test with pure zsh (maybe your config has something special)
- Run this command on your shell: `/usr/bin/env bash` this is the shebang and although I'm fairly sure you probably have `bash` and `env`, there may be something funny happening there.

Apart from this, I don't know what to try, I'm guessing that bash is expanding the value somewhere in the script, but the only way to know is by debugging, and unfortunately I cannot replicate it.

Please tell me if any of that worked.

**Comment by svenXY** [comment]
Nothing helped, whatever I did in zsh and bash, and in whatever terminal (urxvt, xfce4-terminal) and with some different TERM settings (xterm-256color, rxvt-unicode-256color), problem persists.

Since hr.py works fine for me, it is now purely academical, but maybe you are more concerned???

Thanks for your help anyway.

Sven

**Comment by LuRsT** [comment]
Yeah, I'm still worried about it, since if it happened to you, it may happen to someone else in the future, hopefully we'll be able to figure out the problem.

Thanks for your contribution!

**Comment by svenXY** [comment]
Let me know how I can help you further and I'm glad to do so, but I'm out of ideas currently.

**Comment by leoj3n** [comment]
Perhaps try `noglob`? `noglob hr *`
