### ISSUE TITLE
Suggestion: Colour support

### ISSUE THREAD

**Issue by sbrl** [LuRsT/hr#51]
It would make the ruler more visible if I could define a ruler's colour.

**Comment by LuRsT** [comment]
Thank you for the suggestion, you are not the first to make it though, and I'll tell why it hasn't been implemented.

I want to keep `hr` following the [UNIX philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) of doing one thing and one thing well, so changing how the output is displayed in the terminal is not `hr`'s responsability.

I've developed a piece of software that may help you with what you want to accomplish, check [style](https://github.com/LuRsT/style).

**Comment by sbrl** [comment]
Thanks! I'll take a look at it.
